#!/bin/bash

play() {
	./mp "$1" &
	local p=$!
	timeout $2 ffplay -autoexit -loop 1 -showmode 2 $3
	kill -9 $p >&/dev/null
}

./castlevania

play 15sw 27 mm2_dr_wily_s12.mp4
play 16sw 26 last_ninja2_central_park.mp4
play 13sw4sw 26 supaplex.mp4
play 14sw 25 seventh.mp4
play 15sw 29 savage_l2.mp4
play 12sw4sw 22 xenon2.webm
play 16sw 26 uninvited.webm
play 14sw 25 giana.webm
play 11sw4sw 23 '-volume 75 lotus3.webm'
play 15sw 28 cybernoid.mp4
play 8sw4sw 19 '-volume 65 monkey_island.webm'
play 14sw 23 '-volume 90 shadowgate.webm'
play 12sw 27 silver_surfer_stage1.mp4
play 15sw 34 golden_axe_wilderness_title.mp4
