.PHONY: default clean

GFX=\
	adsr.png appleii.jpg bender.jpeg bleeding.png bombe.jpg boot.png \
	breadbin.jpg c1541.jpg c64.jpg c64back.png c64c.jpg c64c_garage.jpg \
	c64schema.jpg c64schema2.jpg datasette.jpg desk.jpg edsac.jpg \
	edsac_crts.jpg farts.png gary.png hvsc.jpg ibm5150.jpg nes.jpg oxo.jpg \
	palette.png pdp8.jpg performance.png pet.jpg pouet.jpg rc3nes.png \
	rekentabellen.jpg rev2017.jpg sbm_obey.png sbm_tuksu.png sprdwh.png \
	sx64.jpg terminator.jpg trs80.jpg vcs.jpg vic20.jpg waveforms.png \
	x.jpg zxspectrum.jpg

default: $(GFX)

adsr.png:
	wget -O adsr.png https://www.garnishmusicproduction.com/wp-content/uploads/2010/10/adsr_envelope_in_dance_music_production1.png
appleii.jpg:
	wget -O appleii.jpg https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Apple_II_IMG_4212.jpg/1024px-Apple_II_IMG_4212.jpg
bender.jpeg:
	wget -O bender.jpeg https://spectrum.ieee.org/image/Mjg5MjEzMg.jpeg
bleeding.gif:
	wget -O bleeding.gif https://upload.wikimedia.org/wikipedia/commons/c/cb/MSX_Computer_Color_Limit.gif
bleeding.png: bleeding.gif
	convert bleeding.gif bleeding.png
bombe.jpg:
	wget -O bombe.jpg 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/%27bombe%27.jpg/960px-%27bombe%27.jpg'
boot.png:
	wget -O boot.png http://www.vanverseveld.me/folkert/c64/workshop/gfx/boot.png
breadbin.jpg:
	wget -O breadbin.jpg http://www.vanverseveld.me/folkert/c64/workshop/gfx/breadbin.jpg
c1541.jpg:
	wget -O c1541.jpg https://upload.wikimedia.org/wikipedia/commons/1/1b/Commodore64_fdd1541_front_demodified.jpg
c64.jpg:
	wget -O c64.jpg https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Commodore-64-Computer-FL.jpg/1024px-Commodore-64-Computer-FL.jpg
c64back.gif:
	wget -O c64back.gif https://www.c64-wiki.com/images/c/cf/C641.gif
c64back.png: c64back.gif
	convert c64back.gif c64back.png
c64c.jpg:
	wget -O c64c.jpg https://www.c64-wiki.com/images/6/6c/C64c.jpg
c64c_garage.jpg:
	wget -O c64c_garage.jpg https://images.hardocp.com/images/news/1475425835dxVq4ZPoJ3_1_1_l.jpg
c64schema.jpg:
	wget -O c64schema.jpg http://www.vanverseveld.me/folkert/c64/workshop/gfx/c64schema.jpg
c64schema2.jpg:
	wget -O c64schema2.jpg http://www.vanverseveld.me/folkert/c64/workshop/gfx/c64schema2.jpg
datasette.jpg:
	wget -O datasette.jpg https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Commodore-Datasette-C2N-Mk2-Front.jpg/1024px-Commodore-Datasette-C2N-Mk2-Front.jpg
desk.jpg:
	wget -O desk.jpg http://studium.chytrak.cz/nostalgia/Setup/Commodore/C-64/C64Pages/HARDWARE/Obr/C64_desk.jpg
edsac.jpg:
	wget -O edsac.jpg 'https://upload.wikimedia.org/wikipedia/commons/2/22/EDSAC_%2819%29.jpg'
edsac_crts.jpg:
	wget -O edsac_crts.jpg https://history-computer.com/ModernComputer/Software/images/EDSAC_CRTs.jpg
farts.png:
	wget -O farts.png https://i.imgur.com/pWpctHO.png
gary.png:
	wget -O gary.png https://www.c64-wiki.com/images/3/3f/Gary_by_Mermaid.png
hvsc.jpg:
	wget -O hvsc.jpg http://hvsc.c64.org/resources/images/HVSC-logo-blue.jpg
ibm5150.jpg:
	wget -O ibm5150.jpg https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Ibm_pc_5150.jpg/827px-Ibm_pc_5150.jpg
nes.jpg:
	wget -O nes.jpg https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/NES-Console-Set.jpg/1024px-NES-Console-Set.jpg
oxo.jpg:
	wget -O oxo.jpg https://i.ytimg.com/vi/irYvQKskBa8/maxresdefault.jpg
palette.png:
	wget -O palette.png http://www.vanverseveld.me/folkert/c64/workshop/gfx/palette.png
pdp8.jpg:
	wget -O pdp8.jpg https://upload.wikimedia.org/wikipedia/commons/6/6d/PDP-8.jpg
performance.png:
	wget -O performance.png http://www.vanverseveld.me/folkert/c64/workshop/gfx/performance.png
pet.jpg:
	wget -O pet.jpg https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Commodore_2001_Series-IMG_0448b.jpg/1024px-Commodore_2001_Series-IMG_0448b.jpg
pouet.jpg:
	wget -O pouet.jpg http://content.pouet.net/logos/logo-9679-01.jpg
rc3nes.png:
	wget -O rc3nes.png http://www.vanverseveld.me/folkert/c64/workshop/gfx/rc3nes.png
rekentabellen.jpg:
	wget -O rekentabellen.jpg https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Abramowitz%26Stegun.page97.agr.jpg/1024px-Abramowitz%26Stegun.page97.agr.jpg
rev2017.jpg:
	wget -O rev2017.jpg https://2017.revision-party.net/media/images/2017/revision-2017-og.jpg
sbm_obey.png:
	wget -O sbm_obey.png https://www.c64-wiki.com/images/1/1e/Obey_The_Machine_by_Archmage.png
sbm_tuksu.png:
	wget -O sbm_tuksu.png https://www.c64-wiki.com/images/c/c2/TTTTTTUUUUUUKSU_by_Duce.png
sprdwh.png:
	wget -O sprdwh.png https://www.c64-wiki.com/images/1/12/Sprite_Vergroesserung.png
sx64.jpg:
	wget -O sx64.jpg http://studium.chytrak.cz/nostalgia/Setup/Commodore/C-64/C64Pages/HARDWARE/Obr/sx64.jpg
terminator.jpg:
	wget -O terminator.jpg http://www.pagetable.com/docs/terminator/t_00-37-23.jpg
trs80.jpg:
	wget -O trs80.jpg https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Radioshack_TRS80-IMG_7206.jpg/1024px-Radioshack_TRS80-IMG_7206.jpg
vcs.jpg:
	wget -O vcs.jpg https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Atari-2600-Wood-4Sw-Set.jpg/1024px-Atari-2600-Wood-4Sw-Set.jpg
vic20.jpg:
	wget -O vic20.jpg https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Commodore-VIC-20-FL.jpg/1024px-Commodore-VIC-20-FL.jpg
waveforms.png:
	wget -O waveforms.png https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Waveforms.svg/892px-Waveforms.svg.png
x.jpg:
	wget -O x.jpg http://www.vanverseveld.me/folkert/c64/workshop/gfx/x.jpg
zxspectrum.jpg:
	wget -O zxspectrum.jpg https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/ZXSpectrum48k.jpg/1024px-ZXSpectrum48k.jpg

clean:
	rm -f *.jpg *.jpeg *.png *.gif
